# Generated by Django 4.2.6 on 2024-01-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_appointment_instructor_appointment_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='user_id',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
