# Generated by Django 4.2.6 on 2024-01-18 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_notation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notation',
            old_name='user_id',
            new_name='user',
        ),
    ]
