# Generated by Django 4.2.6 on 2024-02-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='apartment',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='city_or_village',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='corps',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='house',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='region',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='street',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='group_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='passport_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='passport_series',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='registration',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
