# Generated by Django 4.2.6 on 2024-02-08 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_userdata_apartment_userdata_city_or_village_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='registration',
        ),
    ]
