# Generated by Django 4.2.6 on 2024-02-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_usergroups'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='place_of_birth',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
