# Generated by Django 4.2.6 on 2024-03-29 13:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='payment_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
        ),
    ]
