# Generated by Django 4.2.6 on 2024-03-29 13:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_payments_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
