# Generated by Django 4.2.6 on 2024-03-29 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_payments_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment',
            field=models.FloatField(default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
